chcp 65001
set WORKSPACE=E:\Sourcecode\edk2-202208\edk2
set NASM_PREFIX=C:\NASM\
set IASL_PREFIX=C:\ASL\
set PACKAGES_PATH = %WORKSPACE%\
set CYGWIN_HOME=%WORKSPACE%\BaseTools\Bin\CYGWIN_NT-5.1-i686\
set BASE_TOOLS_PATH=%WORKSPACE%\BaseTools\
set EDK_TOOLS_PATH=%WORKSPACE%\BaseTools